---

# include variables
- name: Include Variables
  include_vars: "{{ ansible_os_family }}.yml"

# Install CalmAV package
- name: Install CalmAV Packages
  apt: name={{ item }} state=installed   update_cache=yes
  with_items: "{{ clamav_packages }}"
  register: pkgs_installed

# start and enable CalmAV daemon 
- name: Start Enable {{ clamav_daemon_name }} daemon 
  service:
    name: "{{ clamav_daemon_name }}"
    state: "{{ clamav_daemon_state }}"
    enabled: "{{ clamav_daemon_enabled }}"

# start enable ClamAV freshclam daemon
- name: Start Enable {{ clamav_freshclam_daemon }} daemon 
  service:
    name: "{{ clamav_freshclam_daemon }}"
    state: "{{ clamav_freshclam_daemon_state }}"
    enabled: "{{ clamav_freshclam_daemon_enabled }}"

## END ##